
    create table tarefa (
        concluida boolean,
        id_tarefa integer generated by default as identity,
        id_usuario integer not null,
        data_criacao timestamp(6),
        descricao varchar(255),
        titulo varchar(255),
        primary key (id_tarefa)
    );

    create table usuario (
        id_usuario integer generated by default as identity,
        nome varchar(255) not null,
        senha varchar(255) not null,
        primary key (id_usuario)
    );

    alter table if exists tarefa 
       add constraint FKky19t41n18yhyhw739ocwwofy 
       foreign key (id_usuario) 
       references usuario;

    create table tarefa (
        concluida boolean,
        id_tarefa integer generated by default as identity,
        id_usuario integer not null,
        data_criacao timestamp(6),
        descricao varchar(255),
        titulo varchar(255),
        primary key (id_tarefa)
    );

    create table usuario (
        id_usuario integer generated by default as identity,
        nome varchar(255) not null,
        senha varchar(255) not null,
        primary key (id_usuario)
    );

    alter table if exists tarefa 
       add constraint FKky19t41n18yhyhw739ocwwofy 
       foreign key (id_usuario) 
       references usuario;

    create table tarefa (
        concluida boolean,
        id_tarefa integer generated by default as identity,
        id_usuario integer not null,
        data_criacao timestamp(6),
        descricao varchar(255),
        titulo varchar(255),
        primary key (id_tarefa)
    );

    create table usuario (
        id_usuario integer generated by default as identity,
        nome varchar(255) not null,
        senha varchar(255) not null,
        primary key (id_usuario)
    );

    alter table if exists tarefa 
       add constraint FKky19t41n18yhyhw739ocwwofy 
       foreign key (id_usuario) 
       references usuario;

    create table tarefa (
        concluida boolean,
        id_tarefa integer generated by default as identity,
        id_usuario integer not null,
        data_criacao timestamp(6),
        descricao varchar(255),
        titulo varchar(255),
        primary key (id_tarefa)
    );

    create table usuario (
        id_usuario integer generated by default as identity,
        nome varchar(255) not null,
        senha varchar(255) not null,
        primary key (id_usuario)
    );

    alter table if exists tarefa 
       add constraint FKky19t41n18yhyhw739ocwwofy 
       foreign key (id_usuario) 
       references usuario;

    create table tarefa (
        concluida boolean,
        id_tarefa integer generated by default as identity,
        id_usuario integer not null,
        data_criacao timestamp(6),
        descricao varchar(255),
        titulo varchar(255),
        primary key (id_tarefa)
    );

    create table usuario (
        id_usuario integer generated by default as identity,
        nome varchar(255) not null,
        senha varchar(255) not null,
        primary key (id_usuario)
    );

    alter table if exists tarefa 
       add constraint FKky19t41n18yhyhw739ocwwofy 
       foreign key (id_usuario) 
       references usuario;
